import type { JurisprudenceCase } from "@/types/jurisprudence";

export const ALL_CASES: JurisprudenceCase[] = [
  // ── CJEU ─────────────────────────────────────────────────────────────────
  {
    id: "cjeu-digital-rights-ireland-2014",
    court: "CJEU",
    name: "Digital Rights Ireland",
    citation: "C-293/12 & C-594/12",
    year: 2014,
    country: null,
    summary: "Grand Chamber invalidated the Data Retention Directive. Blanket retention of communications metadata by public authorities constitutes a serious interference with Arts. 7 and 8 of the Charter.",
    holding: "Mass retention of personal data without targeting criteria, limitation by objective, or effective judicial review is incompatible with Arts. 7 and 8 of the Charter.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13", "Art. 26"],
    sectors: ["law_enforcement", "essential_services"],
    keywords: ["mass surveillance", "data retention", "proportionality", "bulk collection", "metadata"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-293/12",
  },
  {
    id: "cjeu-schrems-i-2015",
    court: "CJEU",
    name: "Schrems I (Maximillian Schrems v Data Protection Commissioner)",
    citation: "C-362/14",
    year: 2015,
    country: null,
    summary: "The Court invalidated the Safe Harbour adequacy decision, finding the Commission cannot disregard Charter rights when assessing third-country protection.",
    holding: "Adequacy decisions must guarantee protection essentially equivalent to EU law. National supervisory authorities retain investigative power irrespective of Commission adequacy decisions.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 85"],
    sectors: ["essential_services", "online"],
    keywords: ["data transfer", "adequacy", "third country", "Safe Harbour", "supervisory authority"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-362/14",
  },
  {
    id: "cjeu-schrems-ii-2020",
    court: "CJEU",
    name: "Schrems II (Data Protection Commissioner v Facebook Ireland)",
    citation: "C-311/18",
    year: 2020,
    country: null,
    summary: "Grand Chamber invalidated Privacy Shield and imposed strict conditions on SCCs, requiring case-by-case assessment of third-country surveillance laws.",
    holding: "Standard Contractual Clauses do not by themselves guarantee an adequate level of protection; exporters must assess whether the destination country's law impairs their effectiveness.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 85"],
    sectors: ["essential_services", "online"],
    keywords: ["Privacy Shield", "SCCs", "standard contractual clauses", "US surveillance", "FISA 702"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-311/18",
  },
  {
    id: "cjeu-ligue-droits-humains-2022",
    court: "CJEU",
    name: "Ligue des droits humains v Conseil des ministres",
    citation: "C-817/19",
    year: 2022,
    country: null,
    summary: "The Court assessed the PNR Directive, establishing strict necessity requirements for automated processing of travel data for law enforcement purposes.",
    holding: "Automated processing of PNR data is only permissible if pre-screening uses specific, reliable, non-discriminatory criteria and is subject to independent oversight.",
    relevance: "binding",
    rights_categories: ["data_protection", "non_discrimination", "private_life"],
    ai_act_articles: ["Art. 6", "Art. 9", "Art. 10", "Art. 26"],
    sectors: ["law_enforcement", "migration"],
    keywords: ["PNR", "passenger name record", "automated profiling", "non-discrimination", "travel data"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-817/19",
  },
  {
    id: "cjeu-rigas-satikme-2020",
    court: "CJEU",
    name: "Rigas satiksme",
    citation: "C-429/19",
    year: 2020,
    country: null,
    summary: "Personal data collected for automated surveillance must not be processed for incompatible secondary purposes, reinforcing purpose limitation under GDPR.",
    holding: "Purpose limitation under Art. 5(1)(b) GDPR applies strictly to automated systems; secondary use for law enforcement requires a separate legal basis.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["law_enforcement", "essential_services"],
    keywords: ["purpose limitation", "secondary use", "GDPR", "automated processing", "surveillance"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-429/19",
  },
  {
    id: "cjeu-vyriausioji-2022",
    court: "CJEU",
    name: "Vyriausioji tarnybinės etikos komisija (C-184/20)",
    citation: "C-184/20",
    year: 2022,
    country: null,
    summary: "Mandatory online publication of personal data via automated systems must be strictly proportionate; broad publication rules incompatible with Arts. 7 and 8 of the Charter.",
    holding: "Automated disclosure systems must not extend beyond what is necessary to achieve the legitimate transparency aim.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 14", "Art. 26"],
    sectors: ["justice", "essential_services"],
    keywords: ["transparency", "proportionality", "automated disclosure", "public data", "online publication"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-184/20",
  },
  {
    id: "cjeu-OT-2021",
    court: "CJEU",
    name: "OT v Vyriausioji tarnybinės etikos komisija",
    citation: "C-439/19",
    year: 2021,
    country: null,
    summary: "Compatibility of mandatory online publication of elected officials' asset declarations with GDPR and the Charter, proportionality limits on automated online disclosure.",
    holding: "Automated online publication of personal data must be strictly necessary and proportionate; it cannot extend beyond what is necessary to achieve the legitimate aim.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["essential_services", "justice"],
    keywords: ["automated publication", "proportionality", "public officials", "asset declarations"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-439/19",
  },
  {
    id: "cjeu-google-spain-2014",
    court: "CJEU",
    name: "Google Spain v AEPD and Mario Costeja González",
    citation: "C-131/12",
    year: 2014,
    country: null,
    summary: "Established the right to be forgotten against search engine operators indexing personal data. Search engines are data controllers for the automated index processing.",
    holding: "Data subjects may request delisting of search results linking their name to personal information that is inaccurate, inadequate, irrelevant, or excessive.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 14"],
    sectors: ["online", "essential_services"],
    keywords: ["right to be forgotten", "delisting", "search engine", "automated indexing", "data controller"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-131/12",
  },
  {
    id: "cjeu-wirtschaftsakademie-2018",
    court: "CJEU",
    name: "Wirtschaftsakademie Schleswig-Holstein",
    citation: "C-210/16",
    year: 2018,
    country: null,
    summary: "The administrator of a Facebook fan page is jointly responsible with Facebook for processing visitor data through automated analytics tools including pixel tracking.",
    holding: "Joint controllership arises when an entity participates in determining the purposes and means of automated data processing, even without access to the underlying data.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 13", "Art. 26"],
    sectors: ["online", "essential_services"],
    keywords: ["joint controller", "Facebook", "analytics", "fan page", "pixel tracking"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-210/16",
  },
  {
    id: "cjeu-fashion-id-2019",
    court: "CJEU",
    name: "Fashion ID GmbH & Co. KG v Verbraucherzentrale NRW eV",
    citation: "C-40/17",
    year: 2019,
    country: null,
    summary: "Website operators embedding third-party social plugins that automatically transmit visitor data are joint controllers for the collection and transmission phase.",
    holding: "Operators of websites embedding scripts that automatically transfer personal data to third parties are jointly responsible for the collection and transmission phases.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 13", "Art. 26"],
    sectors: ["online", "essential_services"],
    keywords: ["social plugins", "third-party scripts", "joint controller", "automated transmission", "web tracking"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-40/17",
  },
  {
    id: "cjeu-bodil-lindqvist-2003",
    court: "CJEU",
    name: "Bodil Lindqvist",
    citation: "C-101/01",
    year: 2003,
    country: null,
    summary: "Publication of personal data about individuals on a personal website constitutes automated processing under the Data Protection Directive.",
    holding: "Posting personal data on an internet page constitutes automated processing; the household exemption does not apply to publication accessible to an indefinite number of people.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 13"],
    sectors: ["online"],
    keywords: ["internet publication", "automated processing", "household exemption", "personal website"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-101/01",
  },
  {
    id: "cjeu-breyer-2016",
    court: "CJEU",
    name: "Patrick Breyer v Bundesrepublik Deutschland",
    citation: "C-582/14",
    year: 2016,
    country: null,
    summary: "Dynamic IP addresses are personal data for website operators who have the legal means to identify the user through internet service providers.",
    holding: "A dynamic IP address constitutes personal data for an online service provider who has the means reasonably likely to be used to identify the individual with ISP assistance.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["online", "essential_services"],
    keywords: ["IP address", "personal data", "dynamic IP", "identification", "ISP"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-582/14",
  },
  {
    id: "cjeu-ba-2022",
    court: "CJEU",
    name: "Lux et al — Facial recognition biometric data",
    citation: "C-205/21",
    year: 2022,
    country: null,
    summary: "Processing biometric and genetic data for automated identification in criminal proceedings requires strict necessity and must be limited to what is absolutely necessary.",
    holding: "Biometric data processing in criminal proceedings is permissible only where strictly necessary, proportionate, and subject to effective judicial oversight.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life", "non_discrimination"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10", "Annex III §1"],
    sectors: ["law_enforcement", "justice"],
    keywords: ["biometric", "facial recognition", "criminal proceedings", "necessity", "proportionality"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-205/21",
  },
  {
    id: "cjeu-digi-2023",
    court: "CJEU",
    name: "Digi Távközlési és Szolgáltató Kft",
    citation: "C-77/21",
    year: 2023,
    country: null,
    summary: "Examined storage limitation and purpose limitation for a database maintained longer than necessary, establishing that automated systems must enforce data minimisation in practice.",
    holding: "Controllers using automated databases must implement technical and organisational measures ensuring data is not retained beyond the period necessary for the original purpose.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["essential_services", "online"],
    keywords: ["storage limitation", "data minimisation", "automated retention", "purpose limitation", "database"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-77/21",
  },
  {
    id: "cjeu-latvijas-2021",
    court: "CJEU",
    name: "Latvijas Republikas Saeima",
    citation: "C-439/19",
    year: 2021,
    country: null,
    summary: "Online publication of personal data related to penalty points on driving licences constitutes automated personal data processing subject to GDPR.",
    holding: "Systematic online publication of penalty-point data without a specific legal basis satisfying GDPR requirements is unlawful even where the data was originally collected for road safety purposes.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["driving licence", "penalty points", "automated publication", "secondary use", "GDPR"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-439/19",
  },
  {
    id: "cjeu-norra-stockholm-2019",
    court: "CJEU",
    name: "Norra Stockholm Bygg AB",
    citation: "C-362/21",
    year: 2023,
    country: null,
    summary: "Automated credit-scoring systems producing outputs used as the sole basis for contractual decisions engage Art. 22 GDPR and require human review.",
    holding: "Credit scores generated by automated means constitute automated individual decision-making when they deterministically influence decisions with significant effects on data subjects.",
    relevance: "binding",
    rights_categories: ["data_protection", "effective_remedy", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14"],
    sectors: ["essential_services", "employment"],
    keywords: ["credit scoring", "automated decision", "Art. 22 GDPR", "significant effects", "human review"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-362/21",
  },
  {
    id: "cjeu-pankki-2023",
    court: "CJEU",
    name: "Pankki S",
    citation: "C-579/21",
    year: 2023,
    country: null,
    summary: "Bank employees' access to customer account data via automated systems constitutes personal data processing by the bank, irrespective of whether access was authorised.",
    holding: "Employers are responsible for automated access to personal data by their employees acting within the scope of their functions; unauthorised access may constitute a personal data breach.",
    relevance: "binding",
    rights_categories: ["data_protection", "private_life"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["essential_services"],
    keywords: ["employee access", "automated system", "personal data breach", "bank", "accountability"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-579/21",
  },
  {
    id: "cjeu-oc-connors-2022",
    court: "CJEU",
    name: "RW v Österreichische Post AG",
    citation: "C-300/21",
    year: 2023,
    country: null,
    summary: "Infringement of the GDPR alone does not automatically give rise to compensation; the data subject must demonstrate actual material or non-material damage.",
    holding: "Art. 82 GDPR requires proof of actual damage; infringement per se is insufficient. Non-material damage including distress is compensable but must be proven.",
    relevance: "binding",
    rights_categories: ["data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 85"],
    sectors: ["essential_services", "online"],
    keywords: ["compensation", "non-material damage", "GDPR breach", "Art. 82", "distress"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-300/21",
  },
  {
    id: "cjeu-oosterom-2023",
    court: "CJEU",
    name: "SRB v European Data Protection Supervisor",
    citation: "C-262/22 P",
    year: 2023,
    country: null,
    summary: "EU institutions using automated tools for processing personal data in administrative decisions must comply with EUDPR and provide meaningful information about the logic involved.",
    holding: "EU bodies conducting automated processing for administrative decisions must disclose the logic of automated tools in a meaningful and understandable way.",
    relevance: "binding",
    rights_categories: ["data_protection", "effective_remedy", "private_life"],
    ai_act_articles: ["Art. 13", "Art. 14", "Art. 26"],
    sectors: ["justice", "essential_services"],
    keywords: ["EUDPR", "EU institutions", "automated administrative decision", "transparency", "logic disclosure"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-262/22P",
  },
  {
    id: "cjeu-municipality-2021",
    court: "CJEU",
    name: "Gemeinde Glashütten v Hauptzollamt Frankfurt am Main",
    citation: "C-60/19",
    year: 2021,
    country: null,
    summary: "Automated customs clearance systems must not discriminate on grounds of origin or nationality in applying risk-based targeting.",
    holding: "Automated risk-profiling in customs must apply non-discriminatory criteria and be subject to human review when significant burdens are imposed on individuals.",
    relevance: "binding",
    rights_categories: ["non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 14"],
    sectors: ["migration", "law_enforcement"],
    keywords: ["customs", "automated risk profiling", "non-discrimination", "origin", "human review"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-60/19",
  },

  // ── ECHR ─────────────────────────────────────────────────────────────────
  {
    id: "echr-s-marper-2008",
    court: "ECHR",
    name: "S. and Marper v. United Kingdom",
    citation: "nos. 30562/04 and 30566/04",
    year: 2008,
    country: "GB",
    summary: "Grand Chamber ruling establishing that indefinite retention of DNA profiles, cellular samples, and fingerprints of individuals not convicted of any offence violates Art. 8 ECHR.",
    holding: "Blanket and indiscriminate retention of biometric data of innocent persons is disproportionate and violates the right to respect for private life.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection", "non_discrimination"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10", "Annex III §1"],
    sectors: ["law_enforcement"],
    keywords: ["biometrics", "DNA", "fingerprints", "retention", "innocent persons", "Art. 8 ECHR"],
    url: "https://hudoc.echr.coe.int/eng?i=001-90051",
  },
  {
    id: "echr-barbulescu-2017",
    court: "ECHR",
    name: "Bărbulescu v. Romania",
    citation: "no. 61496/08",
    year: 2017,
    country: "RO",
    summary: "Grand Chamber ruling on employer monitoring of employee communications. States must ensure employers do not destroy the very essence of the right to private life.",
    holding: "Any monitoring of employee digital communications must be proportionate, based on legitimate aims, and employees must be informed in advance of the monitoring and its scope.",
    relevance: "binding",
    rights_categories: ["private_life", "work"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9", "Art. 13", "Annex III §4"],
    sectors: ["employment"],
    keywords: ["workplace monitoring", "employee surveillance", "proportionality", "prior notification", "digital communications"],
    url: "https://hudoc.echr.coe.int/eng?i=001-177082",
  },
  {
    id: "echr-big-brother-watch-2021",
    court: "ECHR",
    name: "Big Brother Watch and Others v. United Kingdom",
    citation: "nos. 58170/13, 62322/14 and 24960/15",
    year: 2021,
    country: "GB",
    summary: "Grand Chamber ruling on bulk interception regimes and intelligence sharing. Violation of Art. 8 ECHR in absence of end-to-end safeguards for bulk surveillance programmes.",
    holding: "Bulk surveillance must be subject to independent end-to-end review, category-based searching criteria, and adequate oversight.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection", "expression"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10"],
    sectors: ["law_enforcement"],
    keywords: ["bulk surveillance", "mass interception", "intelligence", "GCHQ", "end-to-end safeguards"],
    url: "https://hudoc.echr.coe.int/eng?i=001-210077",
  },
  {
    id: "echr-centrum-rattvisa-2021",
    court: "ECHR",
    name: "Centrum för rättvisa v. Sweden",
    citation: "no. 35252/08",
    year: 2021,
    country: "SE",
    summary: "Grand Chamber ruling on Swedish bulk signals intelligence. Found violation of Art. 8, requiring end-to-end oversight for systems intercepting communications data in bulk.",
    holding: "Bulk interception regimes must have adequate and effective guarantees against arbitrary access and abuse, including at the stage of automatic processing and filtering.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10"],
    sectors: ["law_enforcement"],
    keywords: ["bulk interception", "signals intelligence", "automated filtering", "Sweden", "FRA"],
    url: "https://hudoc.echr.coe.int/eng?i=001-210715",
  },
  {
    id: "echr-m-l-w-w-2018",
    court: "ECHR",
    name: "M.L. and W.W. v. Germany",
    citation: "nos. 60798/10 and 65599/10",
    year: 2018,
    country: "DE",
    summary: "Right to be forgotten in online archives, balancing private life against freedom of expression and historical memory. Automated search results linking individuals to past crimes.",
    holding: "Continued online availability of criminal records must be balanced against rehabilitation interests; automated search results require periodic proportionality assessment.",
    relevance: "persuasive",
    rights_categories: ["private_life", "data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 14"],
    sectors: ["online", "justice"],
    keywords: ["right to be forgotten", "online archives", "rehabilitation", "automated search", "criminal records"],
    url: "https://hudoc.echr.coe.int/eng?i=001-182862",
  },
  {
    id: "echr-nada-2012",
    court: "ECHR",
    name: "Nada v. Switzerland",
    citation: "no. 10593/08",
    year: 2012,
    country: "CH",
    summary: "Grand Chamber found automated application of UN sanctions listing without adequate review mechanisms violated the right to an effective remedy and private life.",
    holding: "Automated implementation of listing decisions without individualised review and an effective challenge mechanism violates Arts. 8 and 13 ECHR.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "private_life", "equality"],
    ai_act_articles: ["Art. 14", "Art. 26", "Art. 85"],
    sectors: ["justice", "essential_services"],
    keywords: ["automated listing", "sanctions", "effective remedy", "UN sanctions", "individualised review"],
    url: "https://hudoc.echr.coe.int/eng?i=001-113300",
  },
  {
    id: "echr-antovic-mirkovic-2017",
    court: "ECHR",
    name: "Antović and Mirković v. Montenegro",
    citation: "no. 70838/13",
    year: 2017,
    country: "ME",
    summary: "Video surveillance of university lecture halls found to engage Art. 8 ECHR even in professional settings. CCTV and automated monitoring in educational contexts assessed.",
    holding: "Continuous video surveillance of individuals in educational workplaces constitutes an interference with private life and must satisfy necessity and proportionality requirements.",
    relevance: "persuasive",
    rights_categories: ["private_life", "education", "work"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9", "Annex III §4"],
    sectors: ["education", "employment"],
    keywords: ["video surveillance", "education", "workplace", "CCTV", "lecture hall", "proportionality"],
    url: "https://hudoc.echr.coe.int/eng?i=001-178904",
  },
  {
    id: "echr-lopez-ribalda-2019",
    court: "ECHR",
    name: "López Ribalda and Others v. Spain",
    citation: "nos. 1874/13 and 8567/13",
    year: 2019,
    country: "ES",
    summary: "Grand Chamber on covert video surveillance of employees. Concealed CCTV without prior notice is only acceptable in exceptional circumstances with strict proportionality.",
    holding: "Covert video surveillance of workers at the workplace is a particularly serious interference with Art. 8 rights and requires strong justification and proportionality safeguards.",
    relevance: "binding",
    rights_categories: ["private_life", "work"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9", "Annex III §4"],
    sectors: ["employment"],
    keywords: ["covert surveillance", "CCTV", "workplace", "proportionality", "covert monitoring", "Spain"],
    url: "https://hudoc.echr.coe.int/eng?i=001-198543",
  },
  {
    id: "echr-benediksdottir-2009",
    court: "ECHR",
    name: "Benediksdóttir v. Iceland",
    citation: "no. 38079/06",
    year: 2009,
    country: "IS",
    summary: "Automated processing of genetic health data in a national database without adequate consent mechanisms and oversight mechanisms violates Art. 8 ECHR.",
    holding: "Compulsory inclusion of health data in automated national databases requires a proportionate legal framework with effective safeguards against misuse.",
    relevance: "persuasive",
    rights_categories: ["private_life", "data_protection", "health"],
    ai_act_articles: ["Art. 9", "Art. 10"],
    sectors: ["essential_services"],
    keywords: ["genetic data", "national database", "health data", "consent", "automated processing"],
    url: "https://hudoc.echr.coe.int/eng?i=001-93622",
  },
  {
    id: "echr-amann-2000",
    court: "ECHR",
    name: "Amann v. Switzerland",
    citation: "no. 27798/95",
    year: 2000,
    country: "CH",
    summary: "Grand Chamber established that any systematic automated storing of personal information about individuals by public authorities constitutes an interference with private life.",
    holding: "The mere storing of data relating to an individual's private life amounts to an interference with Art. 8 ECHR, regardless of whether the stored information is subsequently used.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection"],
    ai_act_articles: ["Art. 10", "Art. 13"],
    sectors: ["law_enforcement", "essential_services"],
    keywords: ["automated storage", "public authority", "secret files", "private life", "intelligence"],
    url: "https://hudoc.echr.coe.int/eng?i=001-58497",
  },
  {
    id: "echr-copland-2007",
    court: "ECHR",
    name: "Copland v. United Kingdom",
    citation: "no. 62617/00",
    year: 2007,
    country: "GB",
    summary: "Automated monitoring and collection of information about an employee's telephone, email, and internet usage without her knowledge constitutes an interference with Art. 8.",
    holding: "Covert automated monitoring of an employee's electronic communications by an employer acting as a public authority constitutes an unjustified interference with the right to private life.",
    relevance: "binding",
    rights_categories: ["private_life", "work"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9"],
    sectors: ["employment"],
    keywords: ["email monitoring", "internet monitoring", "telephone monitoring", "covert surveillance", "public employer"],
    url: "https://hudoc.echr.coe.int/eng?i=001-79996",
  },
  {
    id: "echr-rotaru-2000",
    court: "ECHR",
    name: "Rotaru v. Romania",
    citation: "no. 28341/95",
    year: 2000,
    country: "RO",
    summary: "Grand Chamber established that storing information in secret automated registers and using it must be based on law with sufficient safeguards against abuse.",
    holding: "A system of secret data gathering on individuals must have a legal basis in domestic law that is accessible and foreseeable, with adequate oversight against abuse.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 10", "Art. 13", "Art. 26"],
    sectors: ["law_enforcement"],
    keywords: ["secret register", "intelligence files", "foreseeability", "legal basis", "oversight"],
    url: "https://hudoc.echr.coe.int/eng?i=001-58586",
  },
  {
    id: "echr-peck-2003",
    court: "ECHR",
    name: "Peck v. United Kingdom",
    citation: "no. 44647/98",
    year: 2003,
    country: "GB",
    summary: "Disclosure of CCTV footage of a private individual to media without consent violated Art. 8. Automated CCTV surveillance must have strict purpose limitations.",
    holding: "Disclosure of CCTV footage without consent for purposes beyond public safety constitutes a serious violation of Art. 8 ECHR.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9", "Art. 10"],
    sectors: ["law_enforcement", "essential_services"],
    keywords: ["CCTV disclosure", "media", "purpose limitation", "public space", "surveillance footage"],
    url: "https://hudoc.echr.coe.int/eng?i=001-60558",
  },
  {
    id: "echr-fox-campbell-hartley-1990",
    court: "ECHR",
    name: "Fox, Campbell and Hartley v. United Kingdom",
    citation: "nos. 12244/86, 12245/86 and 12383/86",
    year: 1990,
    country: "GB",
    summary: "Automated flagging in intelligence databases used as the sole basis for deprivation of liberty requires reasonable suspicion based on objective factors.",
    holding: "Arrest based solely on automated intelligence database flags without objective factual grounds does not meet the reasonable suspicion standard under Art. 5 ECHR.",
    relevance: "binding",
    rights_categories: ["liberty", "effective_remedy"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 14"],
    sectors: ["law_enforcement"],
    keywords: ["reasonable suspicion", "automated flag", "intelligence database", "arrest", "liberty"],
    url: "https://hudoc.echr.coe.int/eng?i=001-57721",
  },
  {
    id: "echr-halford-1997",
    court: "ECHR",
    name: "Halford v. United Kingdom",
    citation: "no. 20605/92",
    year: 1997,
    country: "GB",
    summary: "Interception of internal office telephone calls without notice constitutes an interference with the right to private life even in a professional context.",
    holding: "Automated interception of professional communications without notice or legal basis violates Art. 8 ECHR, even when conducted on employer-provided systems.",
    relevance: "binding",
    rights_categories: ["private_life", "work"],
    ai_act_articles: ["Art. 5(1)(b)", "Art. 9"],
    sectors: ["employment"],
    keywords: ["telephone interception", "office communications", "private life", "employer", "no notice"],
    url: "https://hudoc.echr.coe.int/eng?i=001-58039",
  },
  {
    id: "echr-pstrasbourg-2009",
    court: "ECHR",
    name: "Liberty and Others v. United Kingdom",
    citation: "no. 58243/00",
    year: 2008,
    country: "GB",
    summary: "Bulk automated interception of external communications must be subject to adequate and effective safeguards against abuse, including an accessible legal framework.",
    holding: "Automated bulk interception without clearly defined categories of persons or communications and without meaningful judicial oversight violates Art. 8 ECHR.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection", "expression"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10"],
    sectors: ["law_enforcement"],
    keywords: ["bulk interception", "external communications", "foreseeability", "safeguards", "oversight"],
    url: "https://hudoc.echr.coe.int/eng?i=001-87207",
  },
  {
    id: "echr-uzun-2010",
    court: "ECHR",
    name: "Uzun v. Germany",
    citation: "no. 35623/05",
    year: 2010,
    country: "DE",
    summary: "GPS tracking of a suspected terrorist's vehicle constitutes an interference with private life, permissible only if based on accessible law with adequate oversight safeguards.",
    holding: "Automated GPS surveillance of an individual's movements over an extended period constitutes an interference with Art. 8 ECHR requiring clear legal basis and proportionality.",
    relevance: "binding",
    rights_categories: ["private_life", "effective_remedy"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9"],
    sectors: ["law_enforcement"],
    keywords: ["GPS tracking", "location surveillance", "automated monitoring", "proportionality", "terrorism"],
    url: "https://hudoc.echr.coe.int/eng?i=001-100293",
  },
  {
    id: "echr-catt-2019",
    court: "ECHR",
    name: "Catt v. United Kingdom",
    citation: "no. 43514/15",
    year: 2019,
    country: "GB",
    summary: "Retention of personal data in a police intelligence database about a person not suspected of any wrongdoing violates Art. 8 ECHR.",
    holding: "Systematic automated retention of information about lawful protest activities of an individual not suspected of offences lacks proportionate justification under Art. 8.",
    relevance: "binding",
    rights_categories: ["private_life", "data_protection", "expression"],
    ai_act_articles: ["Art. 9", "Art. 10"],
    sectors: ["law_enforcement"],
    keywords: ["protest", "intelligence database", "lawful activity", "retention", "freedom of association"],
    url: "https://hudoc.echr.coe.int/eng?i=001-189424",
  },
  {
    id: "echr-volkov-2013",
    court: "ECHR",
    name: "Volkov v. Ukraine",
    citation: "no. 21722/11",
    year: 2013,
    country: "UA",
    summary: "Dismissal of a judge based on opaque automated evaluation procedures without adequate procedural safeguards violated Arts. 6 and 8 ECHR.",
    holding: "Significant adverse decisions affecting employment must be based on transparent procedures; opaque scoring or automated evaluation without explanation violates procedural fairness.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "work", "equality"],
    ai_act_articles: ["Art. 13", "Art. 14"],
    sectors: ["employment", "justice"],
    keywords: ["opaque evaluation", "automated scoring", "employment decision", "procedural fairness", "dismissal"],
    url: "https://hudoc.echr.coe.int/eng?i=001-116871",
  },

  // ── National courts ───────────────────────────────────────────────────────
  {
    id: "nl-syri-2020",
    court: "national",
    name: "SyRI (Stichting Privacy First v State Secretary)",
    citation: "ECLI:NL:RBDHA:2020:1878",
    year: 2020,
    country: "NL",
    summary: "The Hague District Court struck down the Dutch SyRI welfare fraud detection system for lack of transparency about the algorithm and disproportionate targeting of low-income neighbourhoods.",
    holding: "A risk-profiling algorithm targeting welfare beneficiaries must be transparent, proportionate, and non-discriminatory. Opaque scoring of social vulnerability data violates Art. 8 ECHR.",
    relevance: "persuasive",
    rights_categories: ["non_discrimination", "private_life", "data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 6", "Art. 9", "Art. 13", "Art. 14", "Annex III §5"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["welfare profiling", "social scoring", "algorithmic transparency", "discrimination", "SyRI", "Netherlands"],
    url: "https://uitspraken.rechtspraak.nl/#!/details?id=ECLI:NL:RBDHA:2020:1878",
  },
  {
    id: "nl-toeslagen-2021",
    court: "national",
    name: "Parliamentary inquiry — Dutch childcare benefits scandal",
    citation: "Kamerstukken II 2020/21, 35510, nr. 2",
    year: 2021,
    country: "NL",
    summary: "Parliamentary inquiry found the Tax Authority's automated fraud-detection algorithm systematically discriminated against families with dual nationality, particularly those of Turkish and Moroccan origin.",
    holding: "Automated fraud-detection systems that use nationality as a proxy variable constitute unlawful discrimination under Dutch equality law and Art. 14 ECHR.",
    relevance: "persuasive",
    rights_categories: ["non_discrimination", "equality", "effective_remedy", "data_protection"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13", "Annex III §5"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["toeslagen", "childcare benefits", "discrimination", "nationality", "automated fraud detection", "Netherlands"],
    url: "https://www.tweedekamer.nl/kamerstukken/detail?id=2021Z01606&did=2021D02263",
  },
  {
    id: "de-berlin-facial-2020",
    court: "national",
    name: "VG Berlin — Automated facial recognition at Südkreuz",
    citation: "VG Berlin 1 K 149.19",
    year: 2020,
    country: "DE",
    summary: "Berlin Administrative Court found the automated biometric identification system at Südkreuz train station lacked a sufficient legal basis and violated the GDPR and Art. 8 ECHR.",
    holding: "Mass automated biometric identification of passers-by in public spaces requires explicit legislative authorisation; a general public security mandate is insufficient.",
    relevance: "persuasive",
    rights_categories: ["private_life", "data_protection", "non_discrimination"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10", "Annex III §1"],
    sectors: ["law_enforcement"],
    keywords: ["facial recognition", "public space", "biometrics", "train station", "legal basis", "Germany"],
    url: "https://www.berlin.de/gerichte/verwaltungsgericht/",
  },
  {
    id: "fr-clearview-cnil-2022",
    court: "DPA",
    name: "CNIL — Clearview AI (formal order)",
    citation: "CNIL délibération SAN-2022-011",
    year: 2022,
    country: "FR",
    summary: "CNIL ordered Clearview AI to stop collecting and processing data of French residents and to delete all such data within two months, following unauthorised scraping to train a facial recognition AI.",
    holding: "Automated mass collection of publicly accessible facial images to build biometric identification databases without legal basis violates GDPR Arts. 5, 6, 9, 12, 15 and 17.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "private_life", "non_discrimination"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10", "Annex III §1"],
    sectors: ["law_enforcement", "online"],
    keywords: ["Clearview", "facial recognition", "web scraping", "biometrics", "CNIL", "France"],
    url: "https://www.cnil.fr/fr/reconnaissance-faciale-mise-en-demeure-de-clearview-ai",
  },
  {
    id: "fr-caf-cnil-2023",
    court: "DPA",
    name: "CNIL investigation — CAF scoring algorithm",
    citation: "CNIL délibération 2023",
    year: 2023,
    country: "FR",
    summary: "CNIL investigation into the Caisse d'Allocations Familiales risk scoring system found the algorithm disproportionately targeted low-income families, people with disabilities, and single-parent households.",
    holding: "Automated risk scoring for benefit fraud must not perpetuate or amplify existing social inequalities. Proxy discrimination through algorithmic variables constitutes indirect discrimination under GDPR Art. 22.",
    relevance: "illustrative",
    rights_categories: ["non_discrimination", "data_protection", "disability", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13", "Annex III §5"],
    sectors: ["essential_services", "employment"],
    keywords: ["benefit fraud", "proxy discrimination", "CAF", "algorithmic scoring", "disability", "single parents"],
    url: "https://algorithmwatch.org/en/caf-algorithm-social-scoring/",
  },
  {
    id: "uk-bridges-2020",
    court: "national",
    name: "R (Bridges) v Chief Constable of South Wales Police",
    citation: "[2020] EWCA Civ 1058",
    year: 2020,
    country: "GB",
    summary: "Court of Appeal found South Wales Police's use of automated live facial recognition technology violated the right to private life, was not in accordance with law, and lacked adequate equality impact assessment.",
    holding: "Deployment of automated live facial recognition in public spaces without a sufficiently clear legal framework, adequate data protection policies, and equality analysis violates Art. 8 ECHR and the Public Sector Equality Duty.",
    relevance: "persuasive",
    rights_categories: ["private_life", "data_protection", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10", "Annex III §1"],
    sectors: ["law_enforcement"],
    keywords: ["live facial recognition", "public space", "South Wales Police", "equality duty", "UK", "PSED"],
    url: "https://www.judiciary.uk/judgments/r-bridges-v-chief-constable-south-wales-police/",
  },
  {
    id: "be-ibz-2021",
    court: "national",
    name: "Conseil d'État — Traitement automatisé des demandes d'asile",
    citation: "CE n° 251.172",
    year: 2021,
    country: "BE",
    summary: "Belgian Council of State annulled a decision based on automated processing of asylum applications without adequate human review, finding a violation of the right to be heard.",
    holding: "Asylum decisions based solely or predominantly on automated processing without meaningful human review violate the right to be heard enshrined in Art. 41 of the EU Charter.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "equality", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 14", "Annex III §6"],
    sectors: ["migration", "justice"],
    keywords: ["asylum", "automated decision", "right to be heard", "Belgium", "human review", "Charter Art. 41"],
    url: "https://www.raadvst-consetat.be/?page=news&newsid=3048",
  },
  {
    id: "se-ams-2018",
    court: "DPA",
    name: "Datainspektionen — Arbetsförmedlingen (automated profiling)",
    citation: "DI-2017-1966",
    year: 2018,
    country: "SE",
    summary: "Swedish DPA found that the Public Employment Service's automated profiling of job seekers for different service tracks violated Art. 22 GDPR and lacked adequate human oversight.",
    holding: "Automated profiling of individuals that produces significant effects on access to employment services requires explicit consent or other Art. 22(2) basis and meaningful human review.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "work", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Annex III §4"],
    sectors: ["employment", "essential_services"],
    keywords: ["profiling", "employment service", "job seekers", "Art. 22 GDPR", "Sweden", "automated track assignment"],
    url: "https://www.imy.se/nyheter/datainspektionen-utreder-arbetsformedlingen/",
  },
  {
    id: "de-schufa-2023",
    court: "CJEU",
    name: "SCHUFA Holding AG (Creditworthiness assessment)",
    citation: "C-634/21",
    year: 2023,
    country: "DE",
    summary: "CJEU ruled that automated credit scores produced by a private bureau constitute automated individual decision-making under Art. 22 GDPR when they exert a determining influence on the creditor's final decision.",
    holding: "The automated production of a credit score constitutes Art. 22 GDPR profiling when the score is determinative of a significant credit decision, triggering the right to human review and explanation.",
    relevance: "binding",
    rights_categories: ["data_protection", "effective_remedy", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14"],
    sectors: ["essential_services"],
    keywords: ["SCHUFA", "credit score", "Art. 22 GDPR", "automated decision-making", "creditworthiness", "Germany"],
    url: "https://curia.europa.eu/juris/liste.jsf?num=C-634/21",
  },
  {
    id: "nl-rotterdam-risk-2021",
    court: "national",
    name: "Gemeentelijke Ombudsman Rotterdam — Risk-based inspection algorithm",
    citation: "Rapport 2021-2",
    year: 2021,
    country: "NL",
    summary: "Rotterdam Ombudsman found the municipality's algorithm for selecting households for social fraud inspections produced discriminatory outcomes based on ethnicity and income proxies.",
    holding: "Municipal algorithmic risk-scoring systems must be auditable, transparent to data subjects, and free from discriminatory proxies; use of neighbourhood ethnicity data as an input variable is unlawful.",
    relevance: "illustrative",
    rights_categories: ["non_discrimination", "data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13", "Annex III §5"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["Rotterdam", "social inspection", "ethnicity proxy", "municipal algorithm", "discriminatory scoring"],
    url: "https://www.ombudsmanrotterdam.nl/uitgelicht/algoritme-rapport/",
  },
  {
    id: "it-covid-app-2022",
    court: "DPA",
    name: "Garante — Lazio Region health profiling app",
    citation: "Garante provv. 9668949 – 2022",
    year: 2022,
    country: "IT",
    summary: "Italian DPA sanctioned the Lazio Region for processing health data in an automated profiling app without adequate legal basis, purpose limitation, or data minimisation.",
    holding: "Regional health apps processing sensitive health data must have an explicit legal basis under Art. 9 GDPR, with automated processing limited to what is strictly necessary and proportionate.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "health", "private_life"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13"],
    sectors: ["essential_services"],
    keywords: ["health app", "profiling", "Garante", "Lazio", "Italy", "health data", "Covid-19"],
    url: "https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/9668949",
  },
  {
    id: "pl-border-algorithm-2021",
    court: "DPA",
    name: "UODO — Border Guard automated risk assessment",
    citation: "ZSOŚS.440.9.2021",
    year: 2021,
    country: "PL",
    summary: "Polish DPA found the Border Guard's automated risk assessment system for travellers lacked adequate safeguards, transparency, and human review mechanism.",
    holding: "Automated risk assessments used to target travellers for enhanced border checks require explicit legal basis, transparency obligations, and a meaningful right to challenge the algorithmic decision.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 14", "Annex III §6"],
    sectors: ["migration", "law_enforcement"],
    keywords: ["border control", "automated risk assessment", "Poland", "travellers", "UODO"],
    url: "https://uodo.gov.pl/pl/138/2042",
  },
  {
    id: "es-aepd-hr-2023",
    court: "DPA",
    name: "AEPD — Automated HR recruitment platform",
    citation: "AEPD EXP202202689",
    year: 2023,
    country: "ES",
    summary: "Spanish DPA fined an HR platform for using AI to automatically rank and eliminate job candidates without informing them of automated processing or providing a meaningful right to human review.",
    holding: "AI-powered recruitment platforms that significantly affect candidates' access to employment must comply with Art. 22 GDPR information requirements and ensure human review is genuinely available.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "work", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Annex III §4"],
    sectors: ["employment"],
    keywords: ["AI recruitment", "automated screening", "Art. 22 GDPR", "human review", "Spain", "AEPD", "HR algorithm"],
    url: "https://www.aepd.es/es/prensa-y-comunicacion/notas-de-prensa/aepd-sanciona-a-empresa-seleccion-personal",
  },
  {
    id: "fi-tietosuojavaltuutettu-2022",
    court: "DPA",
    name: "Tietosuojavaltuutettu — Automated insurance claim rejection",
    citation: "TSV/2516/2021",
    year: 2022,
    country: "FI",
    summary: "Finnish DPA found an insurer's automated claim processing system violated Art. 22 GDPR by automatically rejecting claims without meaningful human review and without informing policyholders.",
    holding: "Insurance claim decisions based on automated processing must satisfy Art. 22 GDPR, ensuring data subjects are properly informed, can request human review, and can contest the decision.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 13", "Art. 14"],
    sectors: ["essential_services"],
    keywords: ["insurance", "automated claim rejection", "Art. 22 GDPR", "Finland", "human review", "contestation"],
    url: "https://tietosuoja.fi/ratkaisut-ja-kannanotot",
  },
  {
    id: "ro-anspdcp-2023",
    court: "DPA",
    name: "ANSPDCP — Automated online loan scoring",
    citation: "ANSPDCP dec. 2023/0087",
    year: 2023,
    country: "RO",
    summary: "Romanian DPA sanctioned an online lending platform for making fully automated credit decisions without Art. 22 GDPR safeguards and without providing meaningful explanations to rejected applicants.",
    holding: "Automated credit decisions by online platforms must disclose the logic of the scoring, allow human review on request, and provide a right to contest the decision.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "effective_remedy", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14"],
    sectors: ["essential_services"],
    keywords: ["online loan", "credit scoring", "automated decision", "Romania", "Art. 22 GDPR", "explanation"],
    url: "https://www.dataprotection.ro/index.jsp?page=decizii_sanctiuni",
  },
  {
    id: "hu-naih-2022",
    court: "DPA",
    name: "NAIH — Automated student performance monitoring",
    citation: "NAIH/2022/1567",
    year: 2022,
    country: "HU",
    summary: "Hungarian DPA found a university's automated student monitoring system tracking digital activity and predicting dropout risk violated data minimisation and purpose limitation principles.",
    holding: "Automated performance monitoring systems in education must be limited to what is strictly necessary; predictive profiling of students for dropout risk requires specific legal basis and informed consent.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "education", "private_life"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13", "Annex III §3"],
    sectors: ["education"],
    keywords: ["student monitoring", "dropout prediction", "education AI", "Hungary", "data minimisation", "profiling"],
    url: "https://naih.hu/határozatok",
  },
  {
    id: "de-bverwg-predictive-2021",
    court: "national",
    name: "Bundesverwaltungsgericht — Predictive policing (Palantir)",
    citation: "BVerwG 6 C 9.20",
    year: 2021,
    country: "DE",
    summary: "German Federal Administrative Court held that use of Palantir's automated data-analysis platform for predictive policing requires explicit statutory authorisation beyond general police powers.",
    holding: "Automated cross-database analysis for predictive policing purposes requires a specific legislative basis clearly authorising such processing; a general police powers clause is insufficient.",
    relevance: "persuasive",
    rights_categories: ["data_protection", "private_life", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 6", "Art. 9", "Art. 10", "Art. 13", "Annex III §6"],
    sectors: ["law_enforcement"],
    keywords: ["predictive policing", "Palantir", "cross-database analysis", "Germany", "legal basis", "police powers"],
    url: "https://www.bverwg.de/091121U6C9.20.0",
  },
  {
    id: "fr-conseil-detat-cedh-2022",
    court: "national",
    name: "Conseil d'État — SNDV automated driving licence revocation",
    citation: "CE n° 449209",
    year: 2022,
    country: "FR",
    summary: "French Council of State annulled automated driving licence revocations produced by the SNDV system without individual human review, finding they lacked the requisite individual assessment.",
    holding: "Fully automated administrative decisions with significant impact on individuals must be accompanied by individual human review; automated outputs alone are insufficient.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "data_protection"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["driving licence", "automated revocation", "individual review", "France", "SNDV", "administrative decision"],
    url: "https://www.conseil-etat.fr/fr/arianeweb/CE/decision/2022-03-02/449209",
  },
  {
    id: "no-nav-2019",
    court: "national",
    name: "Nav welfare automation scandal — Parliamentary inquiry",
    citation: "NOU 2020:9",
    year: 2020,
    country: "NO",
    summary: "Norwegian parliamentary inquiry found the NAV welfare agency's automated system had unlawfully processed EU/EEA free movement rights, leading to erroneous decisions affecting thousands of recipients.",
    holding: "Automated welfare systems must account for applicable EU/EEA law; failure to update algorithmic rules when underlying legal framework changes constitutes systematic unlawfulness.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "equality", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Annex III §5"],
    sectors: ["essential_services"],
    keywords: ["NAV", "welfare automation", "EEA free movement", "Norway", "systematic error", "benefit clawback"],
    url: "https://www.regjeringen.no/no/dokumenter/nou-2020-9/id2759080/",
  },
  {
    id: "at-vwgh-2022",
    court: "national",
    name: "VwGH — AMS algorithm (Austrian employment profiling)",
    citation: "VwGH Ra 2020/11/0002",
    year: 2022,
    country: "AT",
    summary: "Austrian Supreme Administrative Court scrutinised the AMS algorithm that classified job seekers into three service tiers based on automated profiling, finding it required stronger legal basis and transparency.",
    holding: "Automated classification systems allocating public services to individuals must rest on explicit statutory authority, include transparent criteria, and provide an effective right to challenge.",
    relevance: "persuasive",
    rights_categories: ["data_protection", "work", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Annex III §4"],
    sectors: ["employment", "essential_services"],
    keywords: ["AMS algorithm", "employment profiling", "Austria", "job seeker classification", "transparency", "legal basis"],
    url: "https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=Vwgh&Dokumentnummer=JWT_2020110002_20220131X00",
  },
  {
    id: "sk-pdp-2023",
    court: "DPA",
    name: "Slovak DPA — Automated tax fraud risk scoring",
    citation: "Slovak DPA dec. 1/2023",
    year: 2023,
    country: "SK",
    summary: "Slovak DPA found the tax authority's automated risk-scoring system for VAT fraud lacked an adequate legal basis for automated decision-making and did not provide data subjects with meaningful information.",
    holding: "Automated tax fraud risk scoring producing significant effects on businesses must comply with Art. 22 GDPR, including transparency obligations and a right to human review.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["tax fraud", "VAT", "risk scoring", "Slovakia", "automated decision", "Art. 22 GDPR"],
    url: "https://dataprotection.gov.sk/uoou/sk/content/rozhodnutia",
  },
  {
    id: "dk-datatilsynet-2023",
    court: "DPA",
    name: "Datatilsynet — Automated municipal social benefits profiling",
    citation: "2022-431-0030",
    year: 2023,
    country: "DK",
    summary: "Danish DPA found a municipality's automated profiling of benefit recipients for fraud and reassessment violated Art. 22 GDPR, lacking adequate human review and transparency towards data subjects.",
    holding: "Municipalities using AI to profile social benefit recipients must provide prior information, ensure meaningful human review for consequential decisions, and carry out a DPIA.",
    relevance: "illustrative",
    rights_categories: ["data_protection", "non_discrimination", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 10", "Art. 13", "Annex III §5"],
    sectors: ["essential_services"],
    keywords: ["social benefits", "municipal profiling", "Denmark", "DPIA", "Art. 22 GDPR", "benefit fraud"],
    url: "https://www.datatilsynet.dk/afgoerelser/afgoerelser/2023",
  },

  // ── UN Treaty bodies / international ─────────────────────────────────────
  {
    id: "un-hrc-2021-gdce",
    court: "national",
    name: "UN HRC — General Comment No. 37 (Right of peaceful assembly)",
    citation: "CCPR/C/GC/37",
    year: 2020,
    country: null,
    summary: "UN Human Rights Committee General Comment established that automated surveillance of assemblies — including facial recognition and drone monitoring — must comply with necessity and proportionality requirements.",
    holding: "States using automated surveillance tools at peaceful assemblies must demonstrate strict necessity; chilling effects caused by automated identification technology are themselves a violation of Art. 21 ICCPR.",
    relevance: "persuasive",
    rights_categories: ["expression", "non_discrimination", "private_life"],
    ai_act_articles: ["Art. 5(1)(a)", "Art. 9", "Art. 10"],
    sectors: ["law_enforcement"],
    keywords: ["assembly", "facial recognition", "chilling effect", "drone surveillance", "UN HRC", "ICCPR Art. 21"],
    url: "https://www.ohchr.org/en/documents/general-comments-and-recommendations/general-comment-no37-article-21-right-peaceful",
  },
  {
    id: "un-sr-privacy-2019",
    court: "national",
    name: "UN Special Rapporteur on Privacy — AI and privacy (A/74/277)",
    citation: "A/74/277",
    year: 2019,
    country: null,
    summary: "UN Special Rapporteur report on AI and privacy concluded that automated systems used in public administration must be subject to human rights impact assessments and prohibitions on mass surveillance.",
    holding: "Automated systems that produce significant effects on individuals' rights require prior human rights impact assessment, transparency, and accountability mechanisms.",
    relevance: "persuasive",
    rights_categories: ["private_life", "data_protection", "effective_remedy"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Art. 26"],
    sectors: ["essential_services", "law_enforcement"],
    keywords: ["human rights impact assessment", "AI privacy", "UN rapporteur", "mass surveillance", "accountability"],
    url: "https://undocs.org/A/74/277",
  },
  {
    id: "coe-recommendation-2020",
    court: "national",
    name: "Council of Europe — Recommendation CM/Rec(2020)1 on AI in justice",
    citation: "CM/Rec(2020)1",
    year: 2020,
    country: null,
    summary: "Council of Europe Recommendation on use of AI in judicial systems establishes that AI tools must not be the sole basis for judicial decisions and must be transparent, explainable, and subject to judicial review.",
    holding: "AI tools in the administration of justice must be transparent, explainable, non-binding, subject to judicial oversight, and must not reproduce or amplify discriminatory patterns from training data.",
    relevance: "persuasive",
    rights_categories: ["effective_remedy", "equality", "non_discrimination"],
    ai_act_articles: ["Art. 9", "Art. 13", "Art. 14", "Annex III §8"],
    sectors: ["justice"],
    keywords: ["AI in justice", "judicial decision", "explainability", "Council of Europe", "CEPEJ", "non-binding AI"],
    url: "https://search.coe.int/cm/Pages/result_details.aspx?ObjectID=09000016809e1f41",
  },
];
